//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmanga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manga
    {
        public int id_manga { get; set; }
        public int id_dessinateur { get; set; }
        public int id_scenariste { get; set; }
        public decimal prix { get; set; }
        public string titre { get; set; }
        public System.DateTime dateParution { get; set; }
        public string couverture { get; set; }
        public int id_genre { get; set; }
    
        public virtual dessinateur dessinateur { get; set; }
        public virtual genre genre { get; set; }
        public virtual scenariste scenariste { get; set; }
    }
}
