//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmanga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public int NumUtil { get; set; }
        public string NomUtil { get; set; }
        public string PrenomUtil { get; set; }
        public string MotPasse { get; set; }
        public string Salt { get; set; }
        public string role { get; set; }
    }
}
